[[redirects]]
  from = "/algod/*"
  to = "http://localhost:4001/:splat"
  status = 200
  force = true
  headers = {X-Algo-Api-Token = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
