name: algokit-explorer
base: core22
version: '0.1'
summary: Short description of your app
description: |
  Detailed description of your app.

confinement: classic
grade: stable

parts:
  algokit-explorer:
    source: snap-dist
    plugin: dump
    build-packages:
      - build-essential
    stage-packages:
      - libgtk-3-0
      - libwebkit2gtk-4.0-37

apps:
  algokit-explorer:
    command: algokit-explorer
    plugs:
      - desktopq
      - desktop-legacy
      - home
      - x11
      - wayland
