name: 'Build for Linux'
inputs:
  release-version:
    description: 'The release version'

runs:
  using: 'composite'
  steps:
    - name: Set ARTIFACT_NAME env variable
      run: echo "ARTIFACT_NAME=algokit-explorer-linux-${{ runner.arch }}" >> $GITHUB_ENV
      shell: bash

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      shell: bash

    - name: Bump version in tauri.conf.json
      if: ${{ inputs.release-version != '' }}
      run: |
        sed -i "s/\"version\": \"0.0.0\"/\"version\": \"${{ inputs.release-version }}\"/g" "src-tauri/tauri.conf.json"
      shell: bash

    - name: Build tauri app
      uses: tauri-apps/tauri-action@v0

    - name: Move binary to target directory
      run: |
        mkdir -p tauri-dist
        mv src-tauri/target/release/algokit-explorer tauri-dist/algokit-explorer
      shell: bash

    # - name: HACK - move binary to target directory
    #   run: |
    #     mkdir -p tauri-dist
    #     cp src/assets/react.svg tauri-dist/algokit-explorer
    #     chmod +x tauri-dist/algokit-explorer
    #   shell: bash

    - name: Zip to preserve permissions
      run: |
        cd tauri-dist
        tar -czvf ../${{ env.ARTIFACT_NAME }}.tar.gz .
      shell: bash

    - name: Upload binary as artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_NAME }}.tar.gz

outputs:
  artifact-name:
    description: 'The name of the artifact'
    value: ${{ env.ARTIFACT_NAME }}.tar.gz
