name: 'Publish to Winget'
description: 'Publish the Windows installer to Winget'
inputs:
  release-version:
    description: 'The release version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Append the msi file to release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: |
          algokit-explorer_*.msi
        tag_name: ${{ inputs.release-version }}
        prerelease: ${{ contains(inputs.release-version, 'beta') }}
