name: 'Build for Linux'
inputs:
  artifacts-path:
    description: 'The path to the artifacts'
    required: true
  linux-artifact-name:
    description: 'The name of the Linux artifact'
    required: true

runs:
  using: 'composite'
  steps:
    - name: debug
      run: |
        ls -R ${{ inputs.artifacts-path }}
      shell: bash

    - name: Generate snapcraft.yaml
      run: |
        ./scripts/snap/create-snapcraft-yaml.sh ${{ github.workspace }} ${{ inputs.release-version }} "stable" "${{ inputs.artifacts-path }}"
      shell: bash

    - name: Build snap
      uses: snapcore/action-build@v1
      with:
        snapcraft-args: --target-arch amd64

    - name: Upload binary as artifact
      id: upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: algokit-explorer-linux-snap
        path: |
          *.snap

    #TODO: in this action, we only publish the snap as an artifact for testing purposes
    # once we have the release token, we will publish the snap to Snap Store
    # - name: Set path to snap binary
    #   shell: bash
    #   run: |
    #     echo "SNAP_BINARY_PATH=$(find ${{ github.workspace }} -name '*.snap')" >> $GITHUB_ENV

    # - name: Publish snap
    #   uses: snapcore/action-publish@v1
    #   env:
    #     SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_RELEASE_TOKEN }}
    #   with:
    #     snap: ${{ env.SNAP_BINARY_PATH }}
    #     release: stable
