name: 'Build for Linux'
inputs:
  release-version:
    description: 'The release version'
    required: true
  artifact-name:
    description: 'The name of the artifact zip file'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Unzip
      run: |
        mkdir -p artifacts
        tar -xzvf ${{ inputs.artifact-name }} -C artifacts
      shell: bash

    - name: Check artifacts dir
      run: |
        ls -R "artifacts"
      shell: bash

    # TODO: this generates a very simple snap, we need to test if it works on a fresh Ubuntu machine
    - name: Generate snapcraft.yaml
      run: |
        ./scripts/snap/create-snapcraft-yaml.sh ${{ github.workspace }} ${{ inputs.release-version }} "stable" "artifacts"
      shell: bash

    - name: Build snap
      uses: snapcore/action-build@v1
      with:
        snapcraft-args: --target-arch amd64

    #TODO: in this action, we only publish the snap as an artifact for testing purposes
    - name: Upload binary as artifact
      id: upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: algokit-explorer-linux-snap
        path: |
          *.snap

    # once we have the release token, we will publish the snap to Snap Store
    # - name: Set path to snap binary
    #   shell: bash
    #   run: |
    #     echo "SNAP_BINARY_PATH=$(find ${{ github.workspace }} -name '*.snap')" >> $GITHUB_ENV

    # - name: Publish snap
    #   uses: snapcore/action-publish@v1
    #   env:
    #     SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_RELEASE_TOKEN }}
    #   with:
    #     snap: ${{ env.SNAP_BINARY_PATH }}
    #     release: stable
