name: 'Build for Ubuntu'
runs:
  using: 'composite'
  steps:
    - name: install dependencies (ubuntu only)
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      shell: bash

    - name: build tauri app
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: algokit-explorer-linux-${{ runner.arch }}
        path: |
          src-tauri/target/release/algokit-explorer
