name: 'Build for Ubuntu'
inputs:
  release-version:
    description: 'The release version'

runs:
  using: 'composite'
  steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      shell: bash

    - name: bump version in tauri.conf.json
      if: ${{ inputs.release-version != '' }}
      run: |
        sed -i "s/\"version\": \"0.0.0\"/\"version\": \"${{ inputs.release-version }}\"/g" "src-tauri/tauri.conf.json"

    - name: build tauri app
      uses: tauri-apps/tauri-action@v0

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: algokit-explorer-linux-${{ runner.arch }}
        path: |
          src-tauri/target/release/algokit-explorer
