name: 'Build for Windows'
inputs:
  production-release:
    description: 'Production release?'
    required: true
  release-version:
    description: 'The release version'

runs:
  using: 'composite'
  steps:
    #  TODO: set up signing certs here when releasing to production

    - name: Set ARTIFACT_NAME env variable
      run: echo "ARTIFACT_NAME=algokit-explorer-windows-${{ runner.arch }}" >> $GITHUB_ENV
      shell: bash

    - name: Bump version in tauri.conf.json
      if: ${{ inputs.release-version != '' }}
      run: |
        version="${{ inputs.release-version }}"
        version="${version/beta./}"
        sed -i "s/\"version\": \"0.0.0\"/\"version\": \"$version\"/g" "src-tauri/tauri.conf.json"
      shell: bash

    - name: Build tauri app
      uses: tauri-apps/tauri-action@v0

    # - name: Move binary to target directory
    #   run: |
    #     mkdir -p windows-dist
    #     mv src-tauri/target/release/*.msi windows-dist/
    #   shell: bash

    # - name: HACK - move binary to target directory
    #   run: |
    #     mkdir -p tauri-dist
    #     cp src/assets/react.svg tauri-dist/algokit-explorer
    #     chmod +x tauri-dist/algokit-explorer
    #   shell: bash

    - name: Upload binary as artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: ${{ env.ARTIFACT_NAME}}
        path: src-tauri/target/release/bundle/msi/algokit-explorer_*.msi

outputs:
  artifact-name:
    description: 'The name of the artifact'
    value: ${{ env.ARTIFACT_NAME }}
