name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.vscode/**'
      - '.idea/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  ci:
    name: CI
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
    with:
      working-directory: .
      node-version: 20.x
      audit-script: npm run audit
      compile-script: npm run check-types
      test-script: npm run tests

  build-website:
    name: Build Website
    uses: makerxstudio/shared-config/.github/workflows/node-build-zip.yml@main
    with:
      build-path: dist
      artifact-name: website
      static-site: true
      static-site-env-prefix: VITE
    needs:
      - ci
